### ISSUE TITLE
Unable to install the extension from Mageplaza

### ISSUE THREAD

**Issue by dmak** [mageplaza/magento-2-twitter-widget#1]
[`README.md`](https://github.com/mageplaza/magento-2-twitter-widget#3-how-to-install-twitter-widget-extension-for-magento-2) reads:
> Run the following command in Magento 2 root folder:
> `composer require mageplaza/module-twitter-widget`

however this results an error:

```
$ composer require mageplaza/module-twitter-widget
                                                                                                                                            
  [InvalidArgumentException]                                                                                                                
  Could not find a matching version of package mageplaza/module-twitter-widget. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```

**Comment by bdtrung** [comment]
Please try this way to install the extension:

- Download [the latest version](https://github.com/mageplaza/magento-2-twitter-widget/archive/master.zip)

- Extract magento-2-twitter-widget-master.zip file to app/code/Mageplaza/TwitterWidget; You should create a folder path app/code/Mageplaza/TwitterWidget if not exist.

- Go to Magento root folder and run upgrade command line to install Mageplaza_TwitterWidget
`php bin/magento setup:upgrade`
`php bin/magento setup:static-content:deploy`

**Comment by dmak** [comment]
It's clear how to set it up manually. However would be nice the plugin to be installed by `composer` as then it could be removed the same way.

**Comment by bdtrung** [comment]
I've tried to install on my local by composer but everything still okay. I'm not sure what wrong on your side so I've instructed you to install by manually.

**Comment by dmak** [comment]
Ah, sorry, I misinterpreted your earlier post. You'd better say "worked for me".

Indeed I tried again and it worked. Sorry, perhaps error in issue description was due to some temporary problem.
